stages:
  process_data:
    cmd: python scripts/process_data.py
    deps:
      - scripts/process_data.py
      - data/raw/v0
      - data/raw/v1
    outs:
      - data/processed/stock_data.parquet

  apply_feast:
    cmd: (cd feature_repo && feast apply)
    deps:
      - feature_repo/features.py
      - feature_repo/feature_store.yaml
    outs:
      - feature_repo/data/registry.db  # Track the registry as an output

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - data/processed/stock_data.parquet
      - feature_repo/data/registry.db
    outs:
      - mlflow.db  # Track the mlflow database as an output
